ALTER TABLE comment
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE comment
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE posts
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE posts
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE posts
    ALTER COLUMN body SET NOT NULL;

ALTER TABLE posts
    ALTER COLUMN title SET NOT NULL;