CREATE TABLE calendar_purchases
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    payment_intent_id VARCHAR(255)                            NOT NULL,
    purchased_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_calendar_purchases PRIMARY KEY (id)
);

ALTER TABLE calendar_purchases
    ADD CONSTRAINT uc_calendar_purchases_payment_intent UNIQUE (payment_intent_id);

ALTER TABLE calendar_purchases
    ADD CONSTRAINT FK_CALENDAR_PURCHASES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);